### ISSUE TITLE
Error while trying to run the sample listed in README

### ISSUE THREAD

**Issue by samgooi4189** [jedld/tensor_stream#4]
I started to experiment with tensor_stream and I got the following error
```
$ ruby sample.rb 
Traceback (most recent call last):
	9: from sample.rb:1:in `<main>'
	8: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	7: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	6: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	5: from /home/samgooi4189/.rvm/gems/ruby-2.5.1@tensorstream/gems/tensor_stream-0.9.9/lib/tensor_stream.rb:43:in `<top (required)>'
	4: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /home/samgooi4189/.rvm/gems/ruby-2.5.1@tensorstream/gems/tensor_stream-0.9.9/lib/tensor_stream/monkey_patches/patch.rb:1:in `<top (required)>'
	1: from /home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/samgooi4189/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- pry-byebug (LoadError)
```

Gemfile.rb:
```
source 'https://rubygems.org'
gem 'tensor_stream'
gem 'tensor_stream-opencl'
```

I resolved the problem by including
`
gem 'pry-byebug'
`
in my Gemfile

Is pry-byebug part of tensor_stream dependencies? Shouldn't it be installed when tensor_stream get installed?

**Comment by jedld** [comment]
Fix on release 0.9.10
