### ISSUE TITLE
Error running rnn.rb sample

### ISSUE THREAD

**Issue by castwide** [jedld/tensor_stream#8]
I get an error `TensorStream::Operation can't be coerced into Integer` when I try to run `bundle exec ruby samples/neural_networks/rnn.rb`. Is there something else I need to do?

Partial output:

```
$ bundle exec ruby samples/neural_networks/rnn.rb
1108 nodes created
New data, epoch0
TensorStream::Operation can't be coerced into Integer
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:94:in `*'
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:94:in `block in fix_inferred_elements'
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:94:in `each'
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:94:in `inject'
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:94:in `fix_inferred_elements'
/home/fred/code/tensor_stream/lib/tensor_stream/tensor_shape.rb:69:in `reshape'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby/array_ops.rb:318:in `block (2 levels) in included'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:134:in `instance_exec'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:134:in `invoke'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:290:in `eval_operation'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:52:in `run'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:72:in `block in complete_eval'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:70:in `loop'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:70:in `complete_eval'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:93:in `prepare_input'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:178:in `global_eval'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:126:in `block in invoke'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:118:in `map'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/base_evaluator.rb:118:in `invoke'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:290:in `eval_operation'
/home/fred/code/tensor_stream/lib/tensor_stream/evaluator/ruby_evaluator.rb:52:in `run'
```

**Comment by jedld** [comment]
Thanks for the report. Should now be fixed in master and the latest release
